In [1]:
import pandas as pd

### <b>DataSet 1:</b> DNRPA - Inscripción Automóviles enero 2022 - Argentina

El primer set de datos seleccionado es sobre la inscripción de automóviles en la <b>Dirección Nacional de los Registros Nacionales de la Propiedad del Automotor (DNRPA)</b> en la República Argentina desde el 01 de enero de 2022 al 31 de enero de 2022.

En este dataset las variables más interesantes son:
  
  - Caracteristicas de vehiculos: Marca, modelo, año.
  - Caracteristicas de personas que realizan el registro: Edad, Sexo, tipo.
  - Cantidad de registros por Localidad.

In [2]:
# dnrpa-inscripciones-iniciales-autos-202201.csv
urlDatasetUno= "https://drive.google.com/uc?id=14Q5P8gJ6iDd6o779HVofh7GxrhJjda-b"
dnrpa = pd.read_csv(urlDatasetUno, sep=";", encoding='iso-8859-1')

In [3]:
dnrpa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43666 entries, 0 to 43665
Data columns (total 23 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   tramite_tipo                    43666 non-null  object
 1   tramite_fecha                   43666 non-null  object
 2   registro_seccional_codigo       43666 non-null  int64
 3   registro_seccional_descripcion  43666 non-null  object
 4   registro_seccional_provincia    43666 non-null  object
 5   automotor_origen                43666 non-null  object
 6   automotor_anio_modelo           43666 non-null  int64
 7   automotor_tipo_codigo           43666 non-null  object
 8   automotor_tipo_descripcion      43666 non-null  object
 9   automotor_marca_codigo          43666 non-null  object
 10  automotor_marca_descripcion     43666 non-null  object
 11  automotor_modelo_codigo         43665 non-null  object
 12  automotor_modelo_descripcion    43666 non-null  object
 13  automotor_uso_codigo            43666 non-null  int64
 14  automotor_uso_descripcion       43666 non-null  object
 15  titular_tipo_persona            43666 non-null  object
 16  titular_domicilio_localidad     43633 non-null  object
 17  titular_domicilio_provincia     43666 non-null  object
 18  titular_genero                  43666 non-null  object
 19  titular_anio_nacimiento         43658 non-null  float64
 20  titular_pais_nacimiento         43666 non-null  object
 21  titular_domicilio_provincia_id  43666 non-null  int64
 22  titular_pais_nacimiento_id      34443 non-null  object
dtypes: float64(1), int64(4), object(18)
memory usage: 7.7+ MB

In [4]:
dnrpa.head()

,tramite_tipo,tramite_fecha,registro_seccional_codigo,registro_seccional_descripcion,registro_seccional_provincia,automotor_origen,automotor_anio_modelo,automotor_tipo_codigo,automotor_tipo_descripcion,automotor_marca_codigo,...,automotor_uso_codigo,automotor_uso_descripcion,titular_tipo_persona,titular_domicilio_localidad,titular_domicilio_provincia,titular_genero,titular_anio_nacimiento,titular_pais_nacimiento,titular_domicilio_provincia_id,titular_pais_nacimiento_id
0,INSCRIPCION INICIAL IMPORTADO,03/01/2022,2087,CAPITAL FEDERAL Nº 087,Ciudad Autónoma de Bs.As.,Importado,2020,C4,PICK-UP CARROZADA,R81,...,1,Privado,Física,C.AUTONOMA DE BS.AS,C.AUTONOMA DE BS.AS,Masculino,1940.0,ARGENTINA,2,ARG
1,INSCRIPCION INICIAL IMPORTADO,03/01/2022,2025,CAPITAL FEDERAL Nº 025,Ciudad Autónoma de Bs.As.,Importado,2021,C4,PICK-UP CARROZADA,R81,...,1,Privado,Jurídica,C.AUTONOMA DE BS.AS,C.AUTONOMA DE BS.AS,No aplica,2008.0,No aplica,2,NaN
2,INSCRIPCION INICIAL IMPORTADO,03/01/2022,1250,ITUZAINGÓ Nº 2 (EX. MORÓN Nº 11),Buenos Aires,Importado,2021,C4,PICK-UP CARROZADA,R81,...,1,Privado,Jurídica,ITUZAINGÓ,BUENOS AIRES,No aplica,2019.0,No aplica,6,NaN
3,INSCRIPCION INICIAL IMPORTADO,03/01/2022,21016,ROSARIO Nº 04,Santa Fe,Importado,2021,99,CHASIS CON CABINA DOBLE,287,...,1,Privado,Jurídica,ROSARIO,SANTA FE,No aplica,1992.0,No aplica,82,NaN
4,INSCRIPCION INICIAL IMPORTADO,03/01/2022,21016,ROSARIO Nº 04,Santa Fe,Importado,2021,99,CHASIS CON CABINA DOBLE,287,...,1,Privado,Jurídica,ROSARIO,SANTA FE,No aplica,1992.0,No aplica,82,NaN

### <b>DataSet 2:</b> Emisiones de gases en centrales eléctricas - 2018 - EEUU

En el segundo set de datos seleccionado se analizan diferentes equipamientos para control de gases contaminantes en diferentes centrales de generación eléctrica en Estados Unidos durante el año 2018.

Las variables importantes en este dataset son:

- PlantID: identificación de la planta.
- Name of Environmental Equipment or Technology Type: tipo de tecnología o equipamiento para control de emisiones.
- Status: manifiesta si está operativo o no.
- Hours in\n Service: horas en servicio.
- FGD Sorbent Quantity \n(thousand tons): cantidad de absorbentes utilizados.
- FGD Electricity\n Consumption \n(Megawatthours): cantidad de absorbentes utilizados por MWh generado.
- Los porcentajes de control eficiente de los diferentes contaminantes.

In [5]:
#Emisiones EUA2018.csv
urlDatasetDos= "https://drive.google.com/uc?id=1CWOIapptFYcAbk-GN9ZXew88tS4xCyU_"

EUA2018 = pd.read_csv(urlDatasetDos, sep=";")

In [6]:
EUA2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7540 entries, 0 to 7539
Data columns (total 23 columns):
 #   Column                                                   Non-Null Count  Dtype
---  ------                                                   --------------  -----
 0   Year                                                     7540 non-null   int64
 1   Plant ID                                                 7540 non-null   int64
 2   Name of Environmental Equipment or Technology Type       7539 non-null   object
 3   PM
 Control ID                                           1867 non-null   object
 4   SO2
 Control ID                                          848 non-null    object
 5   NOX
 Control ID                                          4329 non-null   object
 6   Mercury
 Control                                         1776 non-null   object
 7   Status                                                   7540 non-null   object
 8   Hours in
 Service                                        7540 non-null   object
 9   NOX Emission Rate
 Entire Year
(lbs/MMBtu)              7540 non-null   object
 10  NOX Emission Rate
 May Through September
(lbs/MMBtu)    7540 non-null   object
 11  PM Emissions Rate
(lbs/MMBtu)                           7540 non-null   object
 12  PM Removal Efficiency Rate
 at Annual Operating Factor   7540 non-null   object
 13  PM Tested Efficiency
 Removal at 100% Load               7540 non-null   object
 14  PM Test Date                                             1232 non-null   object
 15  SO2 Removal Efficiency Rate
 at Annual Operating Factor  7540 non-null   object
 16  SO2 Tested Efficiency
 Removal at 100% Load              7540 non-null   object
 17  SO2 Test Date                                            401 non-null    object
 18  FGD Sorbent Quantity
(thousand tons)                    7540 non-null   object
 19  FGD Electricity
 Consumption
(Megawatthours)            7540 non-null   object
 20  Mercury Removal
 Efficiency                              7540 non-null   object
 21  Mercury Emission
 Rate                                   7540 non-null   object
 22  Acid Gas Removal
 Efficiency                             7540 non-null   object
dtypes: int64(2), object(21)
memory usage: 1.3+ MB

In [7]:
EUA2018.head()

,Year,Plant ID,Name of Environmental Equipment or Technology Type,PM\n Control ID,SO2\n Control ID,NOX\n Control ID,Mercury\n Control,Status,Hours in\n Service,NOX Emission Rate\n Entire Year \n(lbs/MMBtu),...,PM Tested Efficiency\n Removal at 100% Load,PM Test Date,SO2 Removal Efficiency Rate\n at Annual Operating Factor,SO2 Tested Efficiency\n Removal at 100% Load,SO2 Test Date,FGD Sorbent Quantity \n(thousand tons),FGD Electricity\n Consumption \n(Megawatthours),Mercury Removal\n Efficiency,Mercury Emission\n Rate,Acid Gas Removal\n Efficiency
0,2018,3,Activated carbon injection system,NaN,NaN,NaN,4,OP,6.248,.,...,.,NaN,.,.,NaN,.,.,.,"0,39",.
1,2018,3,Dry sorbent (powder) injection type (DSI),NaN,NaN,NaN,NaN,OP,6.252,.,...,.,NaN,.,.,NaN,.,.,.,.,.
2,2018,3,"Electrostatic precipitator, cold side, with fl...",5,NaN,NaN,5,OP,6.031,.,...,.,NaN,.,.,NaN,.,.,.,"0,31",.
3,2018,3,"Electrostatic precipitator, cold side, with fl...",4,NaN,NaN,4,OP,6.439,.,...,.,NaN,.,.,NaN,.,.,.,"0,39",.
4,2018,3,"Electrostatic precipitator, hot side, without ...",1,NaN,NaN,NaN,OP,0,.,...,.,NaN,.,.,NaN,.,.,.,.,.

### <b>DataSet 3:</b> Turnos médicos en centros de salud - 2016 - Vitoria ES BR 

En el tercer dataset seleccionado se analizará el presentismo a turnos asignados en distintos centros de salud de la ciudad de Vitoria en el estado de Espirito Santo en Brasil en mayo de 2016. 

Las variables importantes en este dataset son:

  - Datos del paciente: id de paciente, sexo, edad, grado de escolarización.
  - Fecha_turno: fecha en que se asigna turno.
  - SMS_Enviado: Endica si se envió un sms para recordar el turno al paciente.
  - Asiste: Indica si el paciente asistió.
  - Centro_de_Salud: Nombre del centro de salud asignado
  - Historia clinica: se indican datos relativos a la historia clínica del paciente como hipertensión, diabetes, alcoholismo.

In [8]:
#turnos_médicos_Vitoria_ES_BR.csv

urlDatasetTres= "https://drive.google.com/uc?id=1f3QIqx7bocLhxbzYqHo8FLfb_dTtiWu8"

turnosMedicos = pd.read_csv(urlDatasetTres, sep=";")

In [9]:
turnosMedicos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 19 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Nro_turno          110527 non-null  int64
 1   Nro_paciente       110527 non-null  int64
 2   Fecha_Registro     110527 non-null  object
 3   Fecha_turno        110527 non-null  object
 4   SMS_Enviado        110527 non-null  object
 5   Asiste             110527 non-null  object
 6   Centro_de_Salud    110527 non-null  object
 7   Especialidad       110527 non-null  object
 8   Costo Profesional  110527 non-null  int64
 9   Tratamiento        110527 non-null  object
 10  Costo insumos      110527 non-null  int64
 11  Sexo               110527 non-null  object
 12  Edad               110527 non-null  int64
 13  Escolarización     110527 non-null  object
 14  hipertensión       110527 non-null  object
 15  Diabetes           110527 non-null  object
 16  Alcoholismo        110527 non-null  object
 17  Id_discapacidad    110527 non-null  object
 18  Tipo_Discapacidad  110527 non-null  object
dtypes: int64(5), object(14)
memory usage: 16.0+ MB

In [10]:
turnosMedicos.head()

,Nro_turno,Nro_paciente,Fecha_Registro,Fecha_turno,SMS_Enviado,Asiste,Centro_de_Salud,Especialidad,Costo Profesional,Tratamiento,Costo insumos,Sexo,Edad,Escolarización,hipertensión,Diabetes,Alcoholismo,Id_discapacidad,Tipo_Discapacidad
0,5217179,1423328986773,05/01/2016 11:53,29/04/2016,Si,Si,SÃO BENEDITO,CLINICA MEDICA,1200,CONSULTA CLINICA MEDICA,800,M,84,No,Si,Si,No,Si,Grado I
1,5218520,4616857575498,05/01/2016 15:02,29/04/2016,Si,Si,REDENÇÃO,CLINICA MEDICA,1200,CONSULTA CLINICA MEDICA,800,F,83,No,Si,No,No,No,No tiene
2,5235449,55589627937198,11/01/2016 08:52,29/04/2016,Si,Si,MONTE BELO,CLINICA MEDICA,1200,CONSULTA CLINICA MEDICA,800,F,74,No,No,No,No,No,No tiene
3,5235643,91896944762663,11/01/2016 09:08,29/04/2016,Si,Si,GURIGICA,CLINICA MEDICA,1200,CONSULTA CLINICA MEDICA,800,F,70,No,Si,Si,No,No,No tiene
4,5235655,1534481873995,11/01/2016 09:09,29/04/2016,Si,Si,JUCUTUQUARA,CLINICA MEDICA,1200,CONSULTA CLINICA MEDICA,800,F,87,No,No,No,No,No,No tiene